[project]
name = "ai-agent-practice"
version = "0.1.0"
description = "All kind of practicies with ai agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.27",
]
